[package]
name = "sd-jwt-9901"
version.workspace = true
edition = "2021"
description = "An implementation of RFC 9901, Selective Disclosure for JSON Web Tokens"
license.workspace = true
repository.workspace = true

[dependencies]
base64     = { workspace = true }
serde      = { workspace = true }
serde_json = { workspace = true }
thiserror  = { workspace = true }

ed25519-dalek = { version = "2", features = ["rand_core"] }

[dev-dependencies]
rand = "0.8"