[package]
name = "sd-jwt-9901"
description = "An implementation of RFC 9901, Selective Disclosure for JSON Web Tokens"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
base64.workspace = true
serde.workspace = true
serde_json.workspace = true
sha2.workspace = true
thiserror.workspace = true

[lints]
workspace = true
